"""Render the curated CAN layouts; research hypotheses remain explicitly separate."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(catalog):
    lines = ['# BACCAble CAN frame and signal dictionary', '',
             'Generated by `scripts/render_can_dictionary.py` from',
             '[the machine-readable dictionary](../baccable_lab/knowledge/giulia.json).', '',
             f"Dictionary version: **{catalog['dictionary_version']}**. Firmware source snapshot:",
             f"`{catalog['firmware_source_commit']}`.", '',
             f"{len(catalog['messages'])} bus-specific frame descriptions, "
             f"{sum(len(m['signals']) for m in catalog['messages'])} fields and "
             f"{len(catalog['diagnostic_parameters'])} diagnostic catalog entries.", '',
             'For the iterative investigation procedure read [SESSION_ANALYSIS.md](SESSION_ANALYSIS.md)',
             'and the [bundle-first research playbook](RESEARCH_PLAYBOOK.md).',
             'For observations and unresolved claims read the research notes',
             '([initial baseline](research/20260928-findings.md),',
             '[guided-scenario campaign](research/20261010-scenario-sessions.md))',
             'and [the research hypotheses](../baccable_lab/knowledge/hypotheses.json).', '',
             '## Scope and interpretation', '', catalog['vehicle']['scope'], '',
             catalog['byte_convention'], '',
             '`implementation` means a field is decoded or consumed in the source snapshot.',
             '`comment` means only a historical source interpretation.',
             '`capture` is reserved for a reviewed empirical layout with its own evidence.',
             'Origin alone does not prove physical validation. ON/OFF temporal agreement',
             'is supporting evidence; counters,',
             'concurrent actions and conflicting labels can produce false matches.', '',
             'Parts below are concatenated from left to right, most significant part first.',
             'Physical values use the listed scale and offset; these printed numbers are rounded.',
             'The JSON retains the conversion precision and explicit guards.', '']
    for limit in catalog['capture_limits']:
        lines.append('- '+limit)
    lines += ['', '## Broadcast and control reports', '']
    for m in catalog['messages']:
        lines += [f"### {m['role']} {m['can_id']} — {m['title']}", '',
                  'Sources: '+', '.join(f"`{s['path']}`"+(f" (`{s['symbol']}`)" if s.get('symbol') else '') for s in m['sources'])+'.', '']
        if m.get('exact_dlc') is not None:
            lines += [f"Exact DLC required: **{m['exact_dlc']}**.", '']
        observations = m.get('observations', [])
        lines += [f"Observed: {sum(o['frames'] for o in observations):,} frames in {len(observations)} recordings.", '',
                  '| Field | Parts | Conversion / units | Origin | Codes |',
                  '| --- | --- | --- | --- | --- |']
        for s in m['signals']:
            parts = ' + '.join(f'b{b}[{low+width-1}:{low}]' for b,low,width in s['parts'])
            conversion = f"raw × {s['scale']:.6g} + ({s['offset']:.6g}); {s['unit']}"
            enums = ', '.join(f'{k}={v}' for k,v in s.get('enum',{}).items()) or 'Unspecified values stay raw'
            lines.append(f"| `{s['name']}` | `{parts}` | {conversion} | {s['origin']} | {enums} |")
        lines.append('')
        if m.get('note'):
            lines += [m['note'], '']
        for s in m['signals']:
            if s.get('note'):
                lines += [f"`{s['name']}`: {s['note']}", '']
            if s.get('invalid_raw'):
                lines += [f"`{s['name']}`: raw codes excluded by this offline decoder: "
                          + ', '.join(map(str,s['invalid_raw']))+'.', '']
            evidence = s.get('manual_marker_evidence', [])
            if evidence:
                summaries = '; '.join(f"{e['session']}: " + ', '.join(f'{status}={count}' for status,count in e['results'].items()) for e in evidence)
                lines += [f"`{s['name']}` manual-marker evidence: {summaries}. Exact event IDs and raw neighborhoods are in the JSON report.", '']
        if m.get('source_context_labels'):
            for code, context in m['source_context_labels'].items():
                lines += [f"Context `{code}`: **{context['label']}** — {context['provenance']}.", '']
    lines += ['## Diagnostic parameters', '',
              'Passive positive single-frame `0x62` replies only, on C1. Data must satisfy',
              'the declared ISO-TP length, DID and field bounds. Requests are reference',
              'metadata, not commands transmitted by Lab. Unobserved catalog entries are',
              'not proven available on this car. Aliases of one DID are not independent replies.', '',
              'Value = `(raw + raw_offset) × scale + scaled_offset`; value byte offsets',
              'start after the positive-service/DID header. `PCI issue` flags a malformed',
              'source request shape; multi-frame values are not decoded by this implementation.', '',
              '| Parameter | Menu labels | Request → reply ID | DID | Width / offset | Conversion | Request shape |',
              '| --- | --- | --- | --- | --- | --- | --- |']
    for p in catalog['diagnostic_parameters']:
        labels = '; '.join(dict.fromkeys(page['label'] for page in p['menu_pages'])) or '(no menu page)'
        lines.append(f"| {p['parameter_id']} | {labels} | `{p['request_id']} → {p['response_id']}` | `{p['did']}` | {p['width']} / {p['value_offset']} | "
                     f"(raw + {p['raw_offset']}) × {p['scale']:.6g} + {p['scaled_offset']} | {'Consistent' if p['request_shape_valid'] else 'PCI issue'} |")
    lines += ['', '## Inventory of all observed frame shapes', '',
              'Unknown shapes stay unmapped. Counts include useful failed-run data; learned',
              'stable templates use complete runs only. Periods and masks are in the JSON ledger.', '',
              '| Bus | ID | DLC | Frames | Description / coverage |',
              '| --- | --- | --- | --- | --- |']
    for item in catalog.get('observed_inventory', []):
        lines.append(f"| {item['role']} | `{item['can_id']}` | {item['dlc']} | {item['frames']:,} | {item['title'] or item['coverage']} |")
    lines += ['', '## Recorded markers and empirical baselines', '',
              'The JSON `marker_index` links catalog markers and original custom events to',
              'candidate fields and session/event IDs. `no_event_decoder` is an explicit gap,',
              'not evidence that a vehicle function is absent. Derived events stay separate.', '',
              '`frame_templates` combine stable bits across complete recordings; the remaining',
              'bits are variable or unproven. They help spot new behavior on an old identifier.',
              'A single-session template is weaker than repeated observation. Diagnostic IDs',
              'and identity-bearing body-command payloads are excluded from stable-value templates.',
              'Templates never supply a physical meaning for an unknown frame.', '',
              '```sh', 'baccable dictionary --role BH --id 0x46C',
              "baccable dictionary --role BH --id 0x46C --data '00 00 00 00 00 00 04 00'",
              'baccable session decode SESSION --role BH --id 0x46C --limit 20',
              '```', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    catalog = json.loads((ROOT / 'baccable_lab/knowledge/giulia.json').read_text())
    (ROOT / 'docs/CAN_DICTIONARY.md').write_text(render(catalog))
